<?php

/**
 * @file
 * Contains playpoi.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function playpoi_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the playpoi module.
    case 'help.page.playpoi':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Site specific customizations for playpoi.com') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function playpoi_theme() {
  $theme = [];

  return $theme;
}
